### ISSUE TITLE
Errors when running unfi_lab.py

### ISSUE THREAD

**Issue by CISCODUDE** [unifi-hackers/unifi-lab#12]
He guys I am getting this error after running unifi_lab.py

C:........\unifi-lab-master\python unifi_lab.py
installing handler for correct redirect
Traceback (most recent call last):
      File "unifi_lab.py", line 428, in (module)
           main()
      File "unifi_lab.py", line 424, in main
           myUnifiLab.continuousLoop()
      File "unifi_lab.py", line 356, in continuousLoop
           sendMail(errorMessageText % {"error": logError(e)}, self._config)
      File "unifi_lab.py", line 106, in logError
            msg += e.args[0] + "\n"
TypeError: unsupported operand type(s) for +: 'SSLError' and 'str'

Any ideas guys??

Thanks in advance

**Comment by rdalben** [comment]
Try running Python version Python 2.7.6 - 2013-11-10. Mine worked with windows.
 I gave up trying to setup on debian.
