### ISSUE TITLE
How to deal with controller running on non-standard TCP port

### ISSUE THREAD

**Issue by TheMalocchio** [unifi-hackers/unifi-lab#6]
My controller runs at this URL https://10.10.10.10:7443
I changed the base URL in /etc/unifi_lab/unifi_lab_ctlrobj.py
Set the IP in unifi_lab.ini

This is the error I get:
installing handler for correct redirect
Traceback (most recent call last):
  File "/etc/unifi_lab/unifi_lab.py", line 428, in <module>
    main()
  File "/etc/unifi_lab/unifi_lab.py", line 412, in main
    myUniFiLab = UniFiLab(myConfigManager)
  File "/etc/unifi_lab/unifi_lab.py", line 156, in **init**
    self._ctlr.ctlr_login()
  File "/etc/unifi_lab/unifi_lab_ctlrobj.py", line 86, in ctlr_login
    return self.curl ("login", self.make_datastr([["login","login"],["username",self.ctlr_username],["password",self.ctlr_password]]))
  File "/etc/unifi_lab/unifi_lab_ctlrobj.py", line 64, in curl
    uo=urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1215, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

**Comment by rdalben** [comment]
Try running Python version Python 2.7.6 - 2013-11-10. Mine worked with Wndows setup.
 I gave up trying to setup on debian / ubuntu
